"""initial phase 1 spine

Revision ID: ba7301546eb8
Revises: 
Create Date: 2026-09-05 19:16:08.256068
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'ba7301546eb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('rights_grants',
    sa.Column('subject_type', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('MASTER', 'COMPOSITION', 'LYRICS', 'LIKENESS', 'PHOTOGRAPHY', 'VIDEO', 'ARTWORK', 'TRADEMARK', 'DERIVATIVE_EDIT', 'AI_TRANSFORMATION', 'PROMOTIONAL_USE', 'AUDIOVISUAL_USE', name='rightscategory', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('CLEAR', 'RESTRICTED', 'UNKNOWN', 'EXPIRED', name='decisionstatus', native_enum=False), nullable=False),
    sa.Column('grantor', sa.String(length=240), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('territories', sa.JSON(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('restrictions', sa.JSON(), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rights_grants_subject_id'), 'rights_grants', ['subject_id'], unique=False)
    op.create_index(op.f('ix_rights_grants_subject_type'), 'rights_grants', ['subject_type'], unique=False)
    op.create_table('artist_creative_profiles',
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('hard_rules', sa.JSON(), nullable=False),
    sa.Column('descriptors', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id')
    )
    op.create_table('assets',
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('media_type', sa.String(length=40), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_artist_id'), 'assets', ['artist_id'], unique=False)
    op.create_table('tracks',
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_artist_id'), 'tracks', ['artist_id'], unique=False)
    op.create_table('seed_posts',
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.Enum('PUBLISH', 'LEARN', 'ITERATE', 'CAMPAIGN', name='seedmode', native_enum=False), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('learn_from_this', sa.Boolean(), nullable=False),
    sa.Column('create_derivatives', sa.Boolean(), nullable=False),
    sa.Column('gold_reference', sa.Boolean(), nullable=False),
    sa.Column('fingerprint', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_posts_artist_id'), 'seed_posts', ['artist_id'], unique=False)
    op.create_table('track_segments',
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('segment_key', sa.String(length=32), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'segment_key', name='uq_track_segment_key')
    )
    op.create_index(op.f('ix_track_segments_track_id'), 'track_segments', ['track_id'], unique=False)
    op.create_table('audio_use_plans',
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=True),
    sa.Column('track_segment_id', sa.Uuid(), nullable=True),
    sa.Column('strategy', sa.Enum('BAKED_AUDIO', 'PLATFORM_CATALOG_AUDIO', 'OWNED_SOUND', 'PLATFORM_ORIGINAL_SOUND', 'NO_MUSIC', name='audiostrategy', native_enum=False), nullable=False),
    sa.Column('target_platform', sa.String(length=40), nullable=True),
    sa.Column('expected_claim_behavior', sa.Text(), nullable=True),
    sa.Column('platform_sound_ref', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['track_segment_id'], ['track_segments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_use_plans_artist_id'), 'audio_use_plans', ['artist_id'], unique=False)
    op.create_table('creative_concepts',
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('seed_post_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('concept_json', sa.JSON(), nullable=False),
    sa.Column('generator_name', sa.String(length=120), nullable=False),
    sa.Column('generator_version', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seed_post_id'], ['seed_posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creative_concepts_artist_id'), 'creative_concepts', ['artist_id'], unique=False)
    op.create_table('render_plans',
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('audio_use_plan_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('deterministic_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audio_use_plan_id'], ['audio_use_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['concept_id'], ['creative_concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_plans_concept_id'), 'render_plans', ['concept_id'], unique=False)
    op.create_index(op.f('ix_render_plans_deterministic_hash'), 'render_plans', ['deterministic_hash'], unique=False)
    op.create_table('renders',
    sa.Column('render_plan_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('qc_status', sa.Enum('CLEAR', 'RESTRICTED', 'UNKNOWN', 'EXPIRED', name='decisionstatus', native_enum=False), nullable=False),
    sa.Column('qc_report', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['render_plan_id'], ['render_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renders_render_plan_id'), 'renders', ['render_plan_id'], unique=False)
    op.create_table('candidates',
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('render_id', sa.Uuid(), nullable=False),
    sa.Column('audio_use_plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ELIGIBLE', 'REJECTED', 'QUARANTINED', name='candidatestatus', native_enum=False), nullable=False),
    sa.Column('target_platform', sa.String(length=40), nullable=False),
    sa.Column('lineage', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['audio_use_plan_id'], ['audio_use_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['concept_id'], ['creative_concepts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['render_id'], ['renders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_artist_id'), 'candidates', ['artist_id'], unique=False)
    op.create_table('distinctness_decisions',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CLEAR', 'RESTRICTED', 'UNKNOWN', 'EXPIRED', name='decisionstatus', native_enum=False), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('semantic_similarity', sa.Float(), nullable=False),
    sa.Column('visual_similarity', sa.Float(), nullable=False),
    sa.Column('audio_overlap', sa.Float(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distinctness_decisions_candidate_id'), 'distinctness_decisions', ['candidate_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CLEAR', 'RESTRICTED', 'UNKNOWN', 'EXPIRED', name='decisionstatus', native_enum=False), nullable=False),
    sa.Column('rule_version', sa.String(length=80), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_candidate_id'), 'policy_decisions', ['candidate_id'], unique=False)
    op.create_table('publications',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('platform_post_id', sa.String(length=240), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'UPLOADING', 'PROCESSING', 'PUBLISHED', 'MEASURING', 'SETTLED', 'RETRYABLE', 'QUARANTINED', 'REJECTED', name='publicationstatus', native_enum=False), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'idempotency_key', name='uq_publication_idempotency')
    )
    op.create_index(op.f('ix_publications_candidate_id'), 'publications', ['candidate_id'], unique=False)
    op.create_table('rights_decisions',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CLEAR', 'RESTRICTED', 'UNKNOWN', 'EXPIRED', name='decisionstatus', native_enum=False), nullable=False),
    sa.Column('rule_version', sa.String(length=80), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rights_decisions_candidate_id'), 'rights_decisions', ['candidate_id'], unique=False)
    op.create_table('publication_attempts',
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'UPLOADING', 'PROCESSING', 'PUBLISHED', 'MEASURING', 'SETTLED', 'RETRYABLE', 'QUARANTINED', 'REJECTED', name='publicationstatus', native_enum=False), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id', 'attempt_number', name='uq_publication_attempt')
    )
    op.create_index(op.f('ix_publication_attempts_publication_id'), 'publication_attempts', ['publication_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_attempts_publication_id'), table_name='publication_attempts')
    op.drop_table('publication_attempts')
    op.drop_index(op.f('ix_rights_decisions_candidate_id'), table_name='rights_decisions')
    op.drop_table('rights_decisions')
    op.drop_index(op.f('ix_publications_candidate_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_policy_decisions_candidate_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_distinctness_decisions_candidate_id'), table_name='distinctness_decisions')
    op.drop_table('distinctness_decisions')
    op.drop_index(op.f('ix_candidates_artist_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_renders_render_plan_id'), table_name='renders')
    op.drop_table('renders')
    op.drop_index(op.f('ix_render_plans_deterministic_hash'), table_name='render_plans')
    op.drop_index(op.f('ix_render_plans_concept_id'), table_name='render_plans')
    op.drop_table('render_plans')
    op.drop_index(op.f('ix_creative_concepts_artist_id'), table_name='creative_concepts')
    op.drop_table('creative_concepts')
    op.drop_index(op.f('ix_audio_use_plans_artist_id'), table_name='audio_use_plans')
    op.drop_table('audio_use_plans')
    op.drop_index(op.f('ix_track_segments_track_id'), table_name='track_segments')
    op.drop_table('track_segments')
    op.drop_index(op.f('ix_seed_posts_artist_id'), table_name='seed_posts')
    op.drop_table('seed_posts')
    op.drop_index(op.f('ix_tracks_artist_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_assets_artist_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('artist_creative_profiles')
    op.drop_index(op.f('ix_rights_grants_subject_type'), table_name='rights_grants')
    op.drop_index(op.f('ix_rights_grants_subject_id'), table_name='rights_grants')
    op.drop_table('rights_grants')
    op.drop_table('artists')
    # ### end Alembic commands ###
