from enum import StrEnum


class SeedMode(StrEnum):
    PUBLISH = "PUBLISH"
    LEARN = "LEARN"
    ITERATE = "ITERATE"
    CAMPAIGN = "CAMPAIGN"


class RightsCategory(StrEnum):
    MASTER = "MASTER"
    COMPOSITION = "COMPOSITION"
    LYRICS = "LYRICS"
    LIKENESS = "LIKENESS"
    PHOTOGRAPHY = "PHOTOGRAPHY"
    VIDEO = "VIDEO"
    ARTWORK = "ARTWORK"
    TRADEMARK = "TRADEMARK"
    DERIVATIVE_EDIT = "DERIVATIVE_EDIT"
    AI_TRANSFORMATION = "AI_TRANSFORMATION"
    PROMOTIONAL_USE = "PROMOTIONAL_USE"
    AUDIOVISUAL_USE = "AUDIOVISUAL_USE"


class DecisionStatus(StrEnum):
    CLEAR = "CLEAR"
    RESTRICTED = "RESTRICTED"
    UNKNOWN = "UNKNOWN"
    EXPIRED = "EXPIRED"


class AudioStrategy(StrEnum):
    BAKED_AUDIO = "BAKED_AUDIO"
    PLATFORM_CATALOG_AUDIO = "PLATFORM_CATALOG_AUDIO"
    OWNED_SOUND = "OWNED_SOUND"
    PLATFORM_ORIGINAL_SOUND = "PLATFORM_ORIGINAL_SOUND"
    NO_MUSIC = "NO_MUSIC"


class CandidateStatus(StrEnum):
    PLANNED = "PLANNED"
    ELIGIBLE = "ELIGIBLE"
    REJECTED = "REJECTED"
    QUARANTINED = "QUARANTINED"


class PublicationStatus(StrEnum):
    SCHEDULED = "SCHEDULED"
    UPLOADING = "UPLOADING"
    PROCESSING = "PROCESSING"
    PUBLISHED = "PUBLISHED"
    MEASURING = "MEASURING"
    SETTLED = "SETTLED"
    RETRYABLE = "RETRYABLE"
    QUARANTINED = "QUARANTINED"
    REJECTED = "REJECTED"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    RETRYABLE = "RETRYABLE"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    QUARANTINED = "QUARANTINED"


class CapabilitySupport(StrEnum):
    SUPPORTED = "SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    UNKNOWN = "UNKNOWN"
    REQUIRES_PROOF = "REQUIRES_PROOF"


class PlatformProofStatus(StrEnum):
    CREATED = "CREATED"
    READY = "READY"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    MEASURING = "MEASURING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
